### ISSUE TITLE
Bootstrap 3.1

### ISSUE THREAD

**Issue by ernstoarllano** [noahbass/sass-wordpress-bootstrap#4]
Any chance this is going to be updated to the latest version of Bootstrap?

**Comment by noahbass** [comment]
This project is pretty outdated overall. The base for the project comes from [320press/wordpress-bootstrap](https://github.com/320press/wordpress-bootstrap) and that is pretty old as well.

I believe I could add an update to have the latest version of wordpress-bootstrap and the latest bootstrap installed through bower.

**Comment by cinghaman** [comment]
Hi @noahbass any chance you are pushing an update for it?
