### ISSUE TITLE
where is the config.rb file?

### ISSUE THREAD

**Issue by tiagogon** [noahbass/sass-wordpress-bootstrap#5]
Sorry if the question is naif. I'm just starting with SASS and i would expect to see a config.rb file. Am I missing something?

**Comment by noahbass** [comment]
Well, yes you could make yourself a config.rb file and build sass like that.

There is really no set way to build your sass files in this project, I left it more open ended. You could make a config.rb, a gruntfile.js, or just build it like normal sass in the command line: `sass library/sass/bootstrap.scss library/css/bootstrap.css`.

Completely your choice.
